---
name: test workflow job

on:
  workflow_dispatch

jobs:
  edge-test:
    continue-on-error: true
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4
        with:
          ref: test-branch 
          fetch-depth: 0

      - name: Run the tests
        uses: sclorg/testing-farm-as-github-action@v1
        with:
          compose: RHEL-9.4.0-Nightly
          arch: x86_64
          api_key: ${{ secrets.TF_API_KEY }}
          git_url: https://github.com/mcattamoredhat/tmt-demo 
          git_ref: test-branch
          update_pull_request_status: true
          pull_request_status_name: "edge-test-1"
          tf_scope: private
          tmt_plan_regex: edge-mcattamo
          secrets: "DOWNLOAD_NODE=${{ secrets.DOWNLOAD_NODE }}"

